version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: tink-firefly-endpoint
    restart: unless-stopped
    tty: true
    working_dir: /app
    ports:
      - "4444:4444"
      - "80:80"
    volumes:
      - ./:/app
    environment:
      TINK_CLIENT_ID: "YOUR_TINK_CLIENT_ID"
      TINK_CLIENT_SECRET: "YOUR_TINK_CLIENT_SECRET"
      TINK_CALLBACK_URI: "http://localhost:80"
      CSV_PATH: "YOUR_CSV_PATH"
      NOTIFICATIONS_SERVICE_ENDPOINT: "http://notifications.service.endpoint"
      FIREFLY_PERSONAL_ACCESS_TOKEN: "YOUR_FIREFLY_PERSONAL_ACCESS_TOKEN"
      FIREFLY_URL: "YOUR_FIREFLY_URL"
      APP_URL: "YOUR_APP_URL"
    command: [
        "poetry",
        "run",
        "uvicorn",
        "app.main:app",
        "--reload",
        "--host=0.0.0.0",
        "--port=80"
    ]
