version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: tink-homebank-endpoint
    restart: unless-stopped
    tty: true
    working_dir: /app
    ports:
      - "4444:4444"
      - "80:80"
    volumes:
      - ./:/app
    command: [
        "poetry",
        "run",
        "uvicorn",
        "main:app",
        "--reload",
        "--host=0.0.0.0",
        "--port=80"
    ]
