name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      -
        name: Build testing container
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.development_builder.outputs.name }}
          target: development
          load: true
          tags: tink-firefly-endpoint-testing:latest
      -
        name: Run tests
        uses: addnab/docker-run-action@v1
        with:
          image: tink-firefly-endpoint-testing:latest
          shell: sh
          run: sh /app/run_tests_ci ${{ github.sha }} ${{ secrets.CODECOV_TOKEN }}
      -
        name: Set up production Docker Buildx
        id: production_builder_test
        uses: docker/setup-buildx-action@v1
      -
        name: Build production container # This is to know that the production build works
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.production_builder_test.outputs.name }}
          target: production
          tags: namelivia/tink-firefly-endpoint:latest
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
    -
      name: Set up production Docker Buildx
      id: production_builder
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Determine Docker tag
      id: docker_tag
      run: |
        REF="${{ github.ref }}"
        # Check if it's a push to the 'main' branch
        if [[ "$REF" == "refs/heads/main" ]]; then
          echo "TAG=latest" >> $GITHUB_ENV
        # Check if it's a push of a tag
        elif [[ "$REF" =~ ^refs/tags/ ]]; then
          TAG_NAME="${REF#refs/tags/}" # Removes 'refs/tags/' prefix
          echo "TAG=$TAG_NAME" >> $GITHUB_ENV
        else
          echo "Error: Unhandled Git reference type: $REF"
          exit 1
        fi
        echo "Determined Docker TAG: ${{ env.TAG }}"
    -
      name: Build and push production container
      uses: docker/build-push-action@v2
      with:
        push: true
        builder: ${{ steps.production_builder.outputs.name }}
        target: production
        tags: namelivia/tink-firefly-endpoint:${{ env.TAG }}

